feat: added a page for communitiy contribution distribution
lun-dao/LunDAO pull request #69
Opened 2022-01-25 23:39 UTC by yurenju

2022-01-26 02:30 UTC, gasolin approved these changes

2022-01-26 02:30 UTC, gasolin commented on src/pages/community-distribution.md
> +每兩週會由管理者在 [Coordinape][2] 發起分配，在 contributors.csv 業面上的成員可以透過 MetaMask 登入 Coordinape 參與。每個人都會有 100 GIVE 點數分配給其他人。
nit: 兩週 -> 兩月?

2022-01-26 02:30 UTC, gasolin commented on src/pages/community-distribution.md
> +每兩週會由管理者在 [Coordinape][2] 發起分配，在 contributors.csv 業面上的成員可以透過 MetaMask 登入 Coordinape 參與。每個人都會有 100 GIVE 點數分配給其他人。
nit 業面 -> 頁面

2022-01-26 02:30 UTC, gasolin commented on src/pages/community-distribution.md
> +
add date and TX for quick ref check

2022/1/22 https://gnosis-safe.io/app/arb1:0xC2bEeC7a39Ea549F72d937E7b5951B8ee0C8d295/transactions/0x6b8f37ce87b431bb53cf36629bc035cbab9d85a596fbc5c7e328bb708e0ac332

2022-01-26 07:30 UTC, hydai requested changes

2022-01-26 07:30 UTC, hydai commented on src/pages/community-distribution.md
> +|No.|name       |address                                   |5000 LUN distribution|received|sent|epoch number           |Date                   |
因為我們每次都以 Date 來做區分，是不是可以這個表格就直接拿掉 Date 欄位，做成 `2022/01/16-2022/01/21` 的表格就好？
我想像的紀錄資訊：
1. Metadata: On-chain Transactions Hash, Date
2. Table of the LUN distribution

2022-01-26 23:18 UTC, yurenju commented on src/pages/community-distribution.md
> +
我來找找有沒有更容易閱讀的交易 URL，gnosis safe 這個已經比 arbiscan 的好了，但我記得還有另外一個也很清楚的

2022-01-26 23:31 UTC, yurenju commented on src/pages/community-distribution.md
> +
找了一下幾個比較好的都還沒在 Arbitrum 上面，那我就放 Gnosis 跟 Arbiscan 的好了。

2022-01-26 23:33 UTC, yurenju commented on src/pages/community-distribution.md
> +每兩週會由管理者在 [Coordinape][2] 發起分配，在 contributors.csv 業面上的成員可以透過 MetaMask 登入 Coordinape 參與。每個人都會有 100 GIVE 點數分配給其他人。
fixed on commit 3cd4b43410a885cfe2ab7b3227c853b9ece65673

2022-01-26 23:34 UTC, yurenju commented on src/pages/community-distribution.md
> +每兩週會由管理者在 [Coordinape][2] 發起分配，在 contributors.csv 業面上的成員可以透過 MetaMask 登入 Coordinape 參與。每個人都會有 100 GIVE 點數分配給其他人。
fixed on commit 3cd4b43410a885cfe2ab7b3227c853b9ece65673

2022-01-26 23:34 UTC, yurenju commented on src/pages/community-distribution.md
> +
fixed on commit 3cd4b43410a885cfe2ab7b3227c853b9ece65673

2022-01-26 23:34 UTC, yurenju commented on src/pages/community-distribution.md
> +|No.|name       |address                                   |5000 LUN distribution|received|sent|epoch number           |Date                   |
fixed on commit 3cd4b43410a885cfe2ab7b3227c853b9ece65673

2022-01-27 13:49 UTC, hydai approved these changes

2022-01-27 13:49 UTC, merged