新文章：「基本功：从合约看 token 数量」
lun-dao/LunDAO pull request #80
Opened 2022-03-03 10:21 UTC by zjiekai

- 目標讀者：没有solidity开发经验的开发者
- 讀者需具備知識：大概知道以太坊上有 erc20 token 的概念
- 閱讀完畢後讀者會獲得什麼：了解 erc20 的 totalSupply 可以用来查 token 数量

文章比较短，在考虑要不要把最近发现的 [dune 的 bug](https://github.com/duneanalytics/abstractions/issues/875) 加到文章中。

2022-03-03 14:45 UTC, yurenju commented
明天找空來 review 👍  👍  👍

2022-03-03 20:30 UTC, a2468834 commented
題外話 (看作者有沒有意願寫進文章裡面)

(1) $LOOKS 合約的擁有者 (`Ownable.sol` 的 `_owner`，唯一有權利呼叫 `mint()` 函數的地址) 是另一份合約 [1]，裡面應該有實作一些代幣發放的程式邏輯，不過我尚未深究其中內容

(2) $LOOKS 代幣合約似乎沒有 `burn()` 函數，覺得滿奇妙的

(3) 建構子當中的 `_premintReceiver` 變數是傳入一個指向 GnosisSafeProxy 代理合約的地址 [2]，我猜應該是實作多簽錢包吧，尚未深究

---

[1] [0x465a790b428268196865a3ae2648481ad7e0d3b1](https://etherscan.io/address/0x465a790b428268196865a3ae2648481ad7e0d3b1)
[2] [0xb5ea630070d885160323576db6bc86856e40462c](https://etherscan.io/address/0xb5ea630070d885160323576db6bc86856e40462c)

2022-03-04 01:58 UTC, yurenju reviewed
看得差不多了，我有給一些意見給你參考一下。另外 Total Supply 的部分可以要計算一下 burn 的部分，我週末有空會試著用 dune 看看有沒有辦法查出一個端倪，你也可以查查看有沒有辦法找出大致的計算方式

2022-03-04 01:58 UTC, yurenju commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +如果你和我一样，总是担心关注的 token 增发，那就深入合约来探个究竟吧。让我们以最近发行的 Looksrare 项目为例。 可以从 Coingecko 看到有 `Total Supply` 和 `Max Supply` 两个概念。从 Etherscan 的 token 页面又会看到 `Max Total Supply`。 这三个数字并不一致。我并不清楚 Coingecko 和 Ethersc
前面引導讀者的部分可以改善一下，比如說讀者可能知道「發行量」這個東西的意義，因為他會在 coingecko 或是 coinmarketcap 看到，但是他實際上不知道其實只是一個 function 可以直接透過合約查詢，更不知道 totalSupply 可能會變動。

以這樣的前提來說，就可以把以下刪除
> 如果你已经了解 `ERC20` 中 `totalSupply` 本文可能就太罗嗦了。
> function totalSupply() public view returns (uint256)

並且讓關心 token 增發這個因素再多解釋一點，比如說：
> 如果你和我一样，总是担心关注的 token 增发，那就深入合约来探个究竟吧

可以再交代多一點，變成

> 如果你和我一样，总是担心关注的 token 增发，但又對 Coingecko 或 Etherscan 上面的數據充滿疑問，實際上每一個 token 都是一個合約，也就是他是一段程式，所以我們可以用呼叫 function 的方式來查詢。

> 从 Coingecko 看到有 Total Supply 和 Max Supply 两个概念，而从 Etherscan 的 token 页面又会看到 Max Total Supply。 这三个数字并不一致。雖然不清楚 Coingecko 和 Etherscan 的具体机制，但我們直接看看这个 token 的合约吧， Code is Law！

這樣閱讀起來讀者可以順著你的思路來閱讀文章，另外我加的內容都是用繁體中文，如果要用的話會需要檢查一下，把他改成跟整篇文章的用法一致變成簡體中文

2022-03-04 01:58 UTC, yurenju commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +| 2022-01-16 Etherscan 截图 |
這邊可以加上 Etherscan 的連結，因為後面有提到 _cap 的傳入值，這樣讀者可以到那邊找到對應的地方

2022-03-04 01:58 UTC, yurenju commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +| 2022-01-16 Etherscan 截图 |
另外我覺得截圖多加 constructor arguments 也不錯，這樣他下面讀的時候就知道要到哪個分頁下面找對應的資訊

![image](https://user-images.githubusercontent.com/22155/156682116-0f2d42af-2828-44a0-a0cb-8a5a350233c5.png)

2022-03-04 01:58 UTC, yurenju commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +以太坊智能合约部署后，首先运行的就是 `ctor` 函数。可以看出 LOOKS 的 `ctor` 有三个参数。 在 Etherscan 上找出该合约的信息，页面的最下面就是 `Constructor Arguments`。 看到 `_cap` 传入的值为 `1000000000000000000000000000`，这个值除 10^18 就是 1000 mil，就能和 Coingecko 中的`
覺得這邊可以調換一下順序，先給讀者看程式碼，然後再來寫這段解釋 _cap 的部分，另外也可以額外解釋一下 decimals 的用途，然後看到 `1000000000000000000000000000` 這個範例的時候，再跟他們說要算出正確的數值，就是 `_cap/10^decimal`，這樣順著讀就算不知道 decimals 讀到這邊也會理解了

2022-03-04 01:58 UTC, yurenju commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +那么 Coingecko 的 `Total Supply` 又是什么呢？ 这个数字和 Etherscan 的 `Max Total Supply` 是接近的，都是 200+ mil。有理由猜测这是一个动态的数字，两个网站都想监测这个动态数字，但不太同步。有了这个猜想后，再回头看看 LOOKS 的合约。符合 `ERC20` 标准的 token 都有只读函数 `totalSupply()`
Coingecko 的 `Total Supply` 跟 Etherscan 的數字看起來都是要扣掉燒毀的 token，但確實不是很確定這個數字怎麼來的，覺得這邊可以再探究一下大致上的算法可能是怎樣，可以用 dune 看看可不可以把資訊抓出來。

2022-03-04 01:58 UTC, yurenju commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +之前注意到的 `_cap` 只是传给了 `_SUPPLY_CAP` 变量，并没有改变 `_totalSupply`。
這邊可以講一下他合約這樣的行為會有什麼影響

2022-03-04 02:25 UTC, a2468834 requested changes
忘記 submit 了 www

2022-03-04 02:32 UTC, a2468834 requested changes
說明燒毀代幣的機制

2022-03-04 02:32 UTC, a2468834 commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +那么 Coingecko 的 `Total Supply` 又是什么呢？ 这个数字和 Etherscan 的 `Max Total Supply` 是接近的，都是 200+ mil。有理由猜测这是一个动态的数字，两个网站都想监测这个动态数字，但不太同步。有了这个猜想后，再回头看看 LOOKS 的合约。符合 `ERC20` 标准的 token 都有只读函数 `totalSupply()`
確認過整份合約沒有 `burn()` 函數，所以沒有燒毀的問題
p.s. 有包含 openzeppelin 原始 ERC20 模板的 `_burn()` 函數，但它是 internal 型別，不可能由外部合約或 tx 去呼叫

2022-03-04 02:33 UTC, a2468834 commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +| 2022-01-16 Etherscan 截图 |
https://etherscan.io/address/0xf4d2888d29d722226fafa5d9b24f9164c092421e#code

2022-03-05 04:01 UTC, gasolin commented on blog/2022-01-16-total-tokens-looksrare/index.md
> +
可以提一下要查找合約代碼可以前往 Etherscan 或其他鏈上 Explorer，
並解釋一下為什麼有的合約可以找到代碼有的不行 (因為需要合約開發者自行上傳到 Etherscan 才看得到)

2022-03-11 23:12 UTC, a2468834 commented
@zjiekai
你可以直接對 **這個 branch** 修改，原本的留言應該都不會消失掉
剛剛我推了新的 PR，稍後又做了一些修改，才發現到這點

2022-03-12 13:59 UTC, zjiekai commented
感谢大家的建议，我实在太会拖延了

1. 拼写 LooksRare CoinGecko
2. 开头部分，去掉了 totalSupply 的代码，采纳一些修改
3. constructor 截图 修改缩写 ctor；合约链接；decimal
4. 加上说明 view 函数 可以在 Etherscan 上读取 latest block 上的信息
5. 结尾留下一个小问题，一点题外话

mint/burn 之类，就先不提了吧？

2022-03-12 16:46 UTC, a2468834 commented
滿棒的耶，重新看完之後覺得沒有需要增刪的地方了 😄

2022-03-12 17:10 UTC, a2468834 commented
附註：EIP20 在 2015 年已經 final 了，所以文末舉 PowH3D 的例子可能也有吸收到 ERC20 的設計理念

2022-03-13 02:13 UTC, yurenju approved these changes
修改過後我覺得很不錯，我等等就直接合併發布囉！然後我會再補上一些發布時會需要變更的細節

2022-03-13 02:13 UTC, merged